Div/hotfix pagination
NokaK/Online-IliaUni pull request #47
Opened 2021-04-14 15:37 UTC by KetiPilishvili

2021-04-14 16:01 UTC, NokaK commented on index.html
> +   s<section>
s წაუშალე

2021-04-14 16:01 UTC, NokaK commented on js/pagination.js
> +
prettier extension გამოიეყენ კოდი ლამაზად რომ დაგილაგოს

2021-04-14 16:34 UTC, KetiPilishvili commented on index.html
> +   s<section>
ჩავასწორე ნოკა

2021-04-15 16:29 UTC, kristina-makalatia requested changes

2021-04-15 16:29 UTC, kristina-makalatia commented on css/style.css
> +    display: flex;
ქეთი, ხო ბუთსთრაფს იყენებთ გამოიყენე მზა კლასები

2021-04-18 17:46 UTC, NokaK commented on css/style.css
> +    display: flex;
@KetiPilishvili  ამას არ ვასწორებთ ?

2021-04-18 17:48 UTC, NokaK commented
@KetiPilishvili  კონფლიქტია

2021-04-18 18:13 UTC, KetiPilishvili commented on css/style.css
> +    display: flex;
ეს ჩავასწორე

2021-04-18 18:14 UTC, closed without merging